[package]
name = "avl_tree_set_rs"
version = "0.1.0"
authors = ["Francis Murillo <francisavmurillo@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
rand = "0.6.5"
rspec = "1.0.0-beta.4"
fake = "1.3.0"
itertools = "0.8"
quickcheck = "0.8"
quickcheck_macros = "0.8"
